apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-content
  namespace: prod
  labels:
    app: my-content
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-content
  template:
    metadata:
      labels:
        app: my-content
    spec:
      containers:
        - name: my-content
          image: oheneali22/my-content:${TAG}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: my-content-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: my-content-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-content-confignodes
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-content-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-content-config
                  key: DB_NAME
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name:  my-content-service
  namespace: prod
spec:
  selector:
    app:  my-content
  type:  NodePort
  ports:
  - name: my-content-port 
    port:  80
    targetPort:  3000
    nodePort: 30080