name: Real CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show files
      run: ls -la

    - name: Build Docker image
      run: docker build -t my-nginx-app:${{ github.sha }} .

    - name: Test image exists
      run: docker images