name: Runner Investigation

on:
  push:

jobs:
  investigate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Current Directory
      run: pwd

    - name: Current User
      run: whoami

    - name: Operating System
      run: uname -a

    - name: List Files
      run: ls -la

    - name: Create Build Directory
      run: mkdir build

    - name: Create Artifact
      run: echo "Version 1" > build/app.txt

    - name: Verify Artifact
      run: cat build/app.txt